// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Big} level
 * @param {boolean} inletvalve
 * @param {boolean} outletvalve
 * @param {boolean} heater3
 * @param {Big} temp
 * @returns {Promise.<void>}
 */
export async function BoilerAction(level, inletvalve, outletvalve, heater3, temp) {
	// BEGIN USER CODE

	// -------- ELEMENTS --------
	const water = document.getElementById("water");
	const inletFlow = document.getElementById("inletFlow");
	const outletFlow = document.getElementById("outletFlow");
	const steam = document.querySelector(".steam");

	if (!water) return;

	// -------- LEVEL CONVERSION --------
	let targetLevel = level ? level.toNumber() : 0;

	// Safety clamp (0–100)
	targetLevel = Math.max(0, Math.min(100, targetLevel));

	// -------- INITIAL LOAD --------
	if (window.currentLevel === undefined) {
		window.currentLevel = targetLevel;
		water.style.height = targetLevel + "%";
	}

	// -------- STOP OLD ANIMATION --------
	if (window.levelInterval) {
		clearInterval(window.levelInterval);
	}

	// -------- SMOOTH LEVEL ANIMATION --------
	window.levelInterval = setInterval(() => {

		if (window.currentLevel < targetLevel) {
			window.currentLevel += 1;
		} 
		else if (window.currentLevel > targetLevel) {
			window.currentLevel -= 1;
		}

		water.style.height = window.currentLevel + "%";

		// Stop animation when reached
		if (window.currentLevel === targetLevel) {
			clearInterval(window.levelInterval);
		}

	}, 50);

	// -------- INLET FLOW --------
	if (inletvalve === true) {
		inletFlow?.classList.add("active");
	} else {
		inletFlow?.classList.remove("active");
	}

	// -------- OUTLET FLOW --------
	if (outletvalve === true) {
		outletFlow?.classList.add("active");
	} else {
		outletFlow?.classList.remove("active");
	}

	// -------- STEAM EFFECT (FIXED USING HEATER3) --------
	if (steam) {
		if ((temp >= 22 && temp <= 50) && (level > 22)) {
			steam.classList.add("active");
		} else {
			steam.classList.remove("active");
		}
	}

	// END USER CODE
}
